= Recruiting (모집글)
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example request
:operation-http-response-title: Example response


[[recruiting-creat]]
== 모집글 등록

operation::recruiting-creat[snippets='http-request,request-parameters,http-response,response-fields-data']


[[recruiting-detail]]
== 모집글 상세 조회

operation::recruiting-detail[snippets='http-request,request-parameters,http-response,response-fields-data']

[[my-recruiting-list]]
== 내가 쓴 글 목록 조회

operation::my-recruiting-list[snippets='http-request,request-parameters,http-response,response-fields-data']

[[recruiting-recommend-side]]
== 사이드 모집글 추천 목록 조회

operation::recruiting-recommend-side[snippets='http-request,request-parameters,http-response,response-fields-data']

[[recruiting-search-list]]
== 모집글 검색 목록 조회

operation::recruiting-search-list[snippets='http-request,request-parameters,http-response,response-fields-data']

[[recruiting-modify]]
== 모집글 수정

operation::recruiting-modify[snippets='http-request,request-parameters,http-response,response-fields-data']

[[recruiting-remove]]
== 모집글 제거

operation::recruiting-remove[snippets='http-request,request-parameters,http-response,response-fields-data']

[[recruiting-poolup]]
== 모집글 끌올

operation::recruiting-poolup[snippets='http-request,request-parameters,http-response,response-fields-data']